# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-10-31 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=20)),
                ('Category', models.CharField(max_length=20)),
                ('Request', models.CharField(max_length=500)),
                ('Remark', models.CharField(max_length=500)),
                ('From', models.CharField(max_length=50)),
                ('Reference', models.CharField(max_length=50)),
                ('Schedule', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=20)),
                ('Comment', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
            ],
        ),
    ]
