# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-10-31 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwrequests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
