# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwrequests', '0002_auto_20151031_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='Comment',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='Reference',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='Remark',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='Schedule',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='Status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
