# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwrequests', '0003_auto_20151215_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='Comment',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='requests',
            name='Reference',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='requests',
            name='Remark',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='requests',
            name='Schedule',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='requests',
            name='Status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
