# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwrequests', '0006_auto_20151217_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='rank1',
            field=models.ManyToManyField(blank=True, related_name='r1', to='wwrequests.Requests'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='rank2',
            field=models.ManyToManyField(blank=True, related_name='r2', to='wwrequests.Requests'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='rank3',
            field=models.ManyToManyField(blank=True, related_name='r3', to='wwrequests.Requests'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='rank4',
            field=models.ManyToManyField(blank=True, related_name='r4', to='wwrequests.Requests'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='rank5',
            field=models.ManyToManyField(blank=True, related_name='r5', to='wwrequests.Requests'),
        ),
    ]
