# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwrequests', '0007_auto_20151217_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votes',
            old_name='username',
            new_name='user',
        ),
    ]
