# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 09:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwrequests', '0008_auto_20151220_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='From',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
