# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 01:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwrequests', '0011_auto_20151221_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='score',
            new_name='total_score',
        ),
    ]
