# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwrequests', '0012_auto_20151221_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='Request',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
